services:
  backend:
    build: ./backend
    container_name: letter_clinicbackend
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend    
    container_name: letterclinic_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend